[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "clag"
version = "1.0.0"
description = "Controlled Natural Language for Agents"
readme = "README.md"
requires-python = ">=3.12"
license = "CC-BY-NC-SA-4.0"
authors = [
    { name = "Cainan", email = "cainan@example.com" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
dependencies = [
    "antlr4-python3-runtime>=4.13.1",
    "click>=8.1.7",
    "jinja2>=3.1.2",
]

[project.urls]
Homepage = "https://github.com/laca-is/clag"
Repository = "https://github.com/laca-is/clag.git"
Issues = "https://github.com/laca-is/clag/issues"

[project.scripts]
clag = "clag.cli:build" 