from maspy import *
# autogenerated
# (c) cainan - utfpr 2024
class CoffeeMachine(Agent):
    def __init__(self, name = None):
        super().__init__(name)
        self.add(Belief('HasCoffeeBeans'))

    @pl(gain, Goal("MakeExpressoCoffee"), [Belief("HasCoffeeBeans"), Belief('HasCoffeeMachine')])
    def ExpressoReady(self, src):
        print('Expresso Ready')
        self.add(Goal("MakeCoffee"))
        
    @pl(gain, Goal("MakeBlackCoffee"), [Belief("HasCoffeeBeans"), Belief('HasFilter')])
    def BlackReady(self, src):
        print('Black Ready')
        self.add(Goal("MakeCoffee"))

    @pl(lose, Belief("HasFilter"))
    def BuyFilter(self, src):
        print('Buy Filter')
        self.add(Belief("HasFilter"))

    @pl(lose, Belief("HasCoffeeMachine"))
    def FixMachine(self, src):
        print('Fixing coffee machine')
        self.add(Belief("HasCoffeeMachine"))
        
    @pl(gain, Goal("MakeCoffee"))
    def MakeCoffee(self, src):
        print(f'Making coffee.')
        self.stop_cycle()
        
    
# autogenerated
# (c) cainan - utfpr 2024
class CoffeeShop(Environment):
    def __init__(self, name):
        super().__init__(name)
        self.create(Percept('hasCoffee'))

    def buyCoffee(self, src):
        pass

if __name__ == '__main__':
    coffeemachine = CoffeeMachine()
    coffeemachine.add(Belief('HasWater'))
    coffeemachine.add(Belief('HasFilter'))
    coffeemachine.add(Goal('MakeBlackCoffee'))

    Admin().start_system()