lexer grammar ClagLexer;

AGENT:         [aA]'gent';
ENVIRONMENT:   [eE]'nvironment';
CREATE:        [cC]'reate';
AGENTS:        [aA]'gents';
THAT:          [tT]'hat';
BELIEVES:      [bB]'elieves' | [bB]'elieve' | [bB]'elief';
DESIRES:       [dD]'esires' | [dD]'esire';
PERCEIVES:     [pP]'erceives';
WHEN:          [wW]'hen';
THEN:          [tT]'hen';
WITH:          [wW]'ith';
VIA:           [vV]'ia';
TO:            [tT]'o';
IN:            [iI]'n';
USING:         [uU]'sing';
CHANNEL:       [cC]'hannel';
PLANS:         [pP]'lans';
ACTIONS:       [aA]'ctions';
IS:            [iI]'s';
ANY:           [aA]'ny';
LOSES:         [lL]'oses';
ABOUT:         [aA]'bout';
FOCUSING:      [fF]'ocusing';
ON:            [oO]'n';
IGNORING:      [iI]'gnoring';

ACHIEVE:       [aA]'chieve';
UNACHIEVE:     [uU]'nachieve';
ABANDON:       [aA]'bandon';
PERCEPT:       [pP]'ercept';
CHANGE:        [cC]'hange';
REMOVES:       [rR]'emoves';
CREATES:       [cC]'reates';
CHANGES:       [cC]'hanges';
SEND:          [sS]'end';
TELL:          [tT]'ell';
UNTELL:        [uU]'ntell';
HOW:           [hH]'ow';
ASK:           [aA]'sk';
ONE:           [oO]'ne';
ALL:           [aA]'ll';
EVERYONE:      [eE]'veryone';

COMMA:        ',';
DOT:          '.';
AND:          'and' | 'AND';
WAIT:         [wW]'ait';
LPAREN:       '(';
RPAREN:       ')';
ID:           [a-zA-Z_][a-zA-Z0-9_]*;
NUMBER:       '-'? [0-9]+ ('.' [0-9]+)?;
STRING:       '"' ~'"'* '"' | '\'' ~'\''* '\'';
WS:           [ \t\r\n]+ -> skip;